ktor {
  deployment {
    port = 8080
    host = "0.0.0.0"
  }

  application {
    modules = [ ApplicationKt.module ]
  }

  discord {
    token = "MTM3MDcwMzI4MzU2MzI3MDIyNg.G-2kvz.x31WYjmYBCMsX1d7llTVTbXZ1S6U7kqGEYzieE"
  }
}